resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: redis
    image: redis
    ports: 
      - 6379/tcp

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

services:
  redis: redis

strategy:
  matrix:
    node_10_x:
      node_version: 10.x


steps:
  - script: echo "Job Redis_Ping ran and doThing is true."

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run test-with-coverage-azure
    displayName: 'npm test'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/TEST-RESULTS.xml'

  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'